apiVersion: apps/v1
kind: Deployment
metadata:
    name: spring-app

spec:
    replicas: 2

    selector:
        matchLabels:
            app: spring-app

    template:
        metadata:
            labels:
                app: spring-app

        spec:
            containers:
                - name: spring-app
                  image: alialrabi/e-wallet:latest

                  ports:
                      - containerPort: 8091

                  envFrom:

                      # Non-secret configuration
                      - configMapRef:
                            name: app-config

                      # Passwords and credentials
                      - secretRef:
                            name: app-secrets