apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
type: Opaque
stringData:
    DATABASE_USERNAME: walletadmin
    DATABASE_PASSWORD: MazenKarma2026

    KAFKA_USERNAME: avnadmin
    KAFKA_PASSWORD: AVNS_Cnv9k3MeeCZwwTvbcll